### ISSUE TITLE
ExtraLocales disappeared from Kobo eReader.conf

### ISSUE THREAD

**Issue by fromhz** [pgaskin/dictutil#12]
Hello,

I'm using firmware 4.22.15190 with kobopatch (Enable searches on extra dictionaries enabled). When I tried to use my custom dictionaries today, I noticed that they disappeared from the dropdown list.

The dictzip files still exist in ./kobo/dict, but the ExtraLocales in Kobo eReader.conf disappeared.

I tried doing dictutil install again, it worked at first, but then the ExtraLocales disappeared again.

I also tried manually adding to ExtraLocales, same thing happened.

I repatched the firmware and added in the "Never sync dictionaries" patch, same thing happened.

The behavior doesn't depend on the dictionary. I've been using the same setup (firmware version, kobopatch etc) for a while, and this never happened before today.

Thank you!

**Comment by pgaskin** [comment]
Can I see the entire config file (you may want to remove the browser cookies and pocket/dropbox tokens first)? You can email it to me at my email address on my profile.

**Comment by fromhz** [comment]
sent :)

**Comment by pgaskin** [comment]
Which locales are you trying to add?

**Comment by fromhz** [comment]
The conf file I sent you contains "zh, am, br, f1," they've all disappeared at least once today. I've also added te&gu, which disappeared at least once today as well.

**Comment by pgaskin** [comment]
Do you mean they disappear from the config file itself, the menu, or both?

Also, can you type `devmodeon` in the book search, go to Settings/Device/Developer/Log Categories and enable dictionary, try to install a dictionary, send me the new .kobo/syslog-* file, then type `devmodeoff` to put it back to normal?

**Comment by fromhz** [comment]
They disappeared from both the config file and the dropdown list for selecting dictionaries while looking up words within books.

I've sent the log file to your email address.

Thanks :)

**Comment by pgaskin** [comment]
> They disappeared from both the config file and the dropdown list for selecting dictionaries while looking up words within books.

I had a look at the log, and it appears that you connected, added `am`, `br`, and `f1` (`te` was there from the beginning), and looked up words a few times, both inside and outside of books. I don't see any sign of it disappearing from the menu or the config file.

When you say it disappears from the config file, does the `ExtraLocales` line still exist or not?

**Comment by fromhz** [comment]
ExtraLocales line exists with the newest dictionary, but not the older ones that I put in.
i.e. before today, I have the following as ExtraLocales: am,br,f1,te,gu,zh
earlier today,  after I overwrote the te dictionary, and after some unknown magic, I have the following as ExtraLocales: te

From the log file, I concluded that I have the following dictionaries at the following timestamps ( I didn't uninstall any dictionary today)
15:54  te
15:58 am br f1 te zh
16:01 zh
16:05 am br f1 zh (and they haven't disappeared after this time)
I concluded by looking at entries like this:
```
Jul 19 18:26:00 nickel: (NickelMenu) AbstractNickelMenuController::createMenuTextItem(0x3381ca8, `Extra:_zh`, 0, 0, ``) (src/menu.cc:109)
Jul 19 18:26:00 nickel: (NickelMenu) Comparing against 'Settings', 'Dictionary' (src/menu.cc:113)
```

Thank you!

**Comment by pgaskin** [comment]
What happens if you use dictutil v0.3.0?

**Comment by fromhz** [comment]
Actually v0.3.0 is the version I'm using.

**Comment by fromhz** [comment]
Still not sure what caused the issue last time and unable to replicate the issue.
However, it hasn't occurred in the past 10 days, so closing the case.

Thanks for your help :)
