### ISSUE TITLE
Q: How do you deal with encrypted logs?

### ISSUE THREAD

**Issue by BoboTiG** [pgaskin/dictutil#20]
Hello,

I just saw that we no longer have access to raw logs (at least since 2021?). They are [encrypted](https://www.mobileread.com/forums/showpost.php?p=4166564&postcount=5).

So I just wanted to have you inputs on the subject, I guess you used it a lot to debug stuff, right? How do you deal with those logs now?

**Comment by Thovi98** [comment]
Just passing by : I managed to read logs with NickelMenu (https://github.com/pgaskin/dictutil/issues/17#issuecomment-886295645). Did you try ?

**Comment by BoboTiG** [comment]
Wonderful work with NickelMenu, thanks a lot!
